name: Iteminator
description: A modern item editing plugin.
authors: [ TehBrian ]
website: https://github.com/TehBrian/Iteminator

version: ${version}
main: xyz.tehbrian.iteminator.Iteminator
api-version: 1.18

permissions:
  iteminator.format:
    description: Permission to format text.
    default: true
  iteminator.format.minimessage:
    description: Permission to use the MiniMessage formatting type.
    default: op
  iteminator.format.legacy:
    description: Permission to use the Legacy formatting type.
    default: true
  iteminator.reload:
    description: Permission to run /iteminator reload.
    default: op
