name: Iteminator
description: ${description}
authors: [ TehBrian ]
website: https://github.com/TehBrian/Iteminator

version: ${version}
main: dev.tehbrian.iteminator.Iteminator
api-version: "26.1.2"

permissions:
  iteminator.reload:
    description: Permission to reload the plugin.
    default: op

  iteminator.format:
    description: Permission to format text.
    default: true
  iteminator.format.legacy:
    description: Permission to use the legacy formatting type.
    default: true
  iteminator.format.minimessage:
    description: Permission to use the MiniMessage formatting type.
    default: true

  iteminator.edit:
    description: Permission to edit items.
    default: true
  iteminator.edit.amount:
    description: Permission to edit amount.
    default: true
  iteminator.edit.type:
    description: Permission to edit type.
    default: true
  iteminator.edit.unbreakable:
    description: Permission to edit unbreakable.
    default: true
  iteminator.edit.custom-name:
    description: Permission to edit custom name.
    default: true
  iteminator.edit.item-name:
    description: Permission to edit item name.
    default: true
  iteminator.edit.damage-type:
    description: Permission to edit damage type.
    default: true
