name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out sources
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run Gradle build
        run: ./gradlew build --no-daemon
